# Generated by Django 4.1.5 on 2023-01-23 10:52

import accounts.utils
from django.db import migrations, models
import employee.utils


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_rename_empoloyeeinfo_employeeinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='joining_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='photo',
            field=models.ImageField(default='default/user.jpg', height_field=300, upload_to=accounts.utils.user_directory_path, validators=[employee.utils.validate_image_type, employee.utils.validate_image_file_size], width_field=300),
        ),
    ]
