# Generated by Django 4.1.5 on 2023-01-23 11:04

import accounts.utils
from django.db import migrations, models
import employee.utils


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employeeinfo_joining_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='photo',
            field=models.ImageField(height_field=300, upload_to=accounts.utils.user_directory_path, validators=[employee.utils.validate_image_type, employee.utils.validate_image_file_size], width_field=300),
        ),
    ]
