# Generated by Django 4.1.5 on 2023-02-14 10:07

from django.db import migrations, models
import django.db.models.deletion
import employee.utils


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employeeinfo_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(choices=[('HR', 'Human Resource'), ('administrative', 'Administrative'), ('software development', 'Software Development'), ('QA', 'Quality Assurance'), ('project management', 'Project Management'), ('Product Management', 'Product Management'), ('design', 'Design'), ('devOps', 'DevOps'), ('customer support', 'Customer Support'), ('marketing', 'Marketing'), ('IT', 'Information Technology')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employeeinfo',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employeeinfo',
            name='job_title',
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='photo',
            field=models.ImageField(upload_to=employee.utils.user_directory_path, validators=[employee.utils.validate_image_type, employee.utils.validate_image_file_size, employee.utils.validate_image_dimention]),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='signature',
            field=models.ImageField(upload_to=employee.utils.user_directory_path, validators=[employee.utils.validate_image_type, employee.utils.validate_signature_image_file_size, employee.utils.validate_image_signature_dimention]),
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.designationinfo'),
        ),
    ]
