# Generated by Django 4.1.5 on 2023-03-31 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0008_socialmedialink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Poor(1)'), (2, 'Fair(1)'), (3, 'Good(1)'), (4, 'Very Good(1)'), (5, 'Excellent(1)')])),
                ('subject', models.CharField(max_length=100)),
                ('review_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('review_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_by', to=settings.AUTH_USER_MODEL)),
                ('review_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_of', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
