# Generated by Django 4.1.5 on 2023-02-15 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('meet_from', models.TimeField()),
                ('meet_to', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('cancel_status', models.BooleanField(default=False)),
                ('cancel_message', models.CharField(blank=True, max_length=200, null=True)),
                ('appointment_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
