# Generated by Django 4.1.5 on 2023-02-18 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('request_date', models.DateField()),
                ('approved_date', models.DateField()),
                ('heading', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('accept_status', models.BooleanField(default=False)),
                ('meeting_time', models.TimeField(blank=True)),
                ('message', models.TextField()),
                ('decline_status', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('appointment_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_from', to='appointment.appointment')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_by', to=settings.AUTH_USER_MODEL)),
                ('request_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
