# Generated by Django 4.1.5 on 2023-03-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointmentapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='cancel_message',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='cancel_status',
        ),
        migrations.AddField(
            model_name='appointmentapplication',
            name='cancel_message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appointmentapplication',
            name='cancel_status',
            field=models.BooleanField(default=False),
        ),
    ]
