# Generated by Django 4.1.5 on 2023-03-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_appointment_visiting_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentapplication',
            name='heading',
            field=models.CharField(max_length=100),
        ),
    ]
