# Generated by Django 4.1.5 on 2023-03-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_alter_appointmentapplication_approved_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentapplication',
            name='meeting_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
