# Generated by Django 4.1.5 on 2023-03-23 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0007_alter_appointmentapplication_meeting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentapplication',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issued_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
