# Generated by Django 4.1.5 on 2023-03-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_alter_appointmentapplication_issued_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentapplication',
            name='request_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
