# Generated by Django 4.1.5 on 2023-03-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_alter_appointmentapplication_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentapplication',
            name='cancel_message',
            field=models.TextField(),
        ),
    ]
