# Generated by Django 4.1.5 on 2023-03-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_alter_appointmentapplication_cancel_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentapplication',
            name='cancel_message',
            field=models.TextField(null=True),
        ),
    ]
