# Generated by Django 4.1.5 on 2023-03-24 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_alter_appointmentapplication_cancel_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentapplication',
            name='cancel_message',
        ),
    ]
