# Generated by Django 4.1.5 on 2023-03-29 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0015_appointmentapplication_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnArivalAppointmentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_by', models.CharField(max_length=50)),
                ('national_id', models.CharField(max_length=20)),
                ('phone_no', models.CharField(max_length=15)),
                ('appointment_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('issued_status', models.BooleanField(default=False)),
                ('entering_time', models.TimeField(null=True)),
                ('exit_time', models.TimeField(null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('appointment_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onarival_appointment', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onarival_issued_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
