# Generated by Django 4.1.5 on 2023-03-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0016_onarivalappointmentapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='onarivalappointmentapplication',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='onarivalappointmentapplication',
            name='appointment_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='onarivalappointmentapplication',
            name='designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onarivalappointmentapplication',
            name='occupation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
