# Generated by Django 4.1.5 on 2023-03-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0017_onarivalappointmentapplication_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onarivalappointmentapplication',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
