# Generated by Django 4.1.5 on 2023-03-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0018_onarivalappointmentapplication_email_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='onarivalappointmentapplication',
            name='photo',
            field=models.ImageField(null=True, upload_to='appointment/'),
        ),
    ]
