# Generated by Django 4.1.5 on 2023-03-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0020_alter_onarivalappointmentapplication_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onarivalappointmentapplication',
            name='photo',
            field=models.ImageField(null=True, upload_to='appointment/'),
        ),
    ]
