# Generated by Django 4.1.5 on 2023-01-16 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_emplyee',
            new_name='is_employee',
        ),
    ]
