# Generated by Django 4.1.5 on 2023-01-18 10:02

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_is_emplyee_user_is_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default/user.jpg', null=True, upload_to=accounts.utils.user_directory_path),
        ),
    ]
