# Generated by Django 4.1.5 on 2023-01-19 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_permanentaddress_post_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permanentaddress',
            old_name='city',
            new_name='division',
        ),
        migrations.RenameField(
            model_name='permanentaddress',
            old_name='district',
            new_name='permanent_district',
        ),
        migrations.RenameField(
            model_name='permanentaddress',
            old_name='police_station',
            new_name='upzila',
        ),
        migrations.RenameField(
            model_name='permanentaddress',
            old_name='post_code',
            new_name='zip_code',
        ),
    ]
