# Generated by Django 4.1.5 on 2023-03-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_receptonist',
            field=models.BooleanField(default=False),
        ),
    ]
