# Generated by Django 4.1.5 on 2023-01-18 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('national_id', models.CharField(blank=True, max_length=20)),
                ('passport_no', models.CharField(blank=True, max_length=30)),
                ('occupation', models.CharField(blank=True, max_length=50)),
                ('designation', models.CharField(blank=True, max_length=50)),
                ('organization', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True, max_length=200)),
                ('organization_address', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
