# Generated by Django 4.1.5 on 2023-01-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_alter_visitorinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorinfo',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
