# Generated by Django 4.1.5 on 2023-01-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0003_alter_visitorinfo_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorinfo',
            name='designation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='visitorinfo',
            name='occupation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='visitorinfo',
            name='passport_no',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='visitorinfo',
            name='phone_no',
            field=models.CharField(max_length=15),
        ),
    ]
