# Generated by Django 4.1.5 on 2023-03-20 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitor', '0004_alter_visitorinfo_designation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('link_of', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_link', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
